version: '3'

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes: 
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network


  wordpress:
    depends_on: 
      - db
    image: wordpress:5.1.1-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - app-network


  webserver:
    depends_on:
      - wordpress
    image: nginx:1.15.12-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:433"
    volumes:
      - wordpress:/var/www/html
      - /nginx-conf/nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
    networks:
      - app-network


  step-cli:
    container_name: cli
    image: smallstep/step-cli
    ports:
      - "88:88"
    volumes:
      - certbot-etc:/etc/letsencrypt
      - ./roots.pem:/home/step/roots.pem
      - wordpress:/var/www/html
    dns:
      - 192.168.146.60
    command: step ca certificate --root=/home/step/roots.pem --provisioner=acme --http-listen=88 --ca-url=https://ca.pki.project wordpress.pki.project /etc/letsencrypt/cert.pem /etc/letsencrypt/key.pem


volumes:
  certbot-etc:
  wordpress:
  dbdata:

networks:
  app-network:
    driver: bridge




  # certbot:
  #   depends_on:
  #     - webserver
  #   image: certbot/certbot
  #   container_name: certbot
  #   # environment:
  #     # - REQUEST_CA_BUNDLE=/
  #   volumes:
  #     - certbot-etc:/etc/letsencrypt
  #     - wordpress:/var/www/html
  #   dns:
  #     - 192.168.146.60
  #   command: certonly --webroot --webroot-path=/var/www/html --server https://ca.pki.project:9000/acme/acme/directory --email kelvin.bogaerts02@gmail.com --agree-tos --no-eff-email -d wordpress.pki.project -d www.wordpress.pki.project
