version: '3'

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes: 
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network


  wordpress:
    depends_on: 
      - db
    image: wordpress:5.1.1-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - app-network


  webserver:
    depends_on:
      - wordpress
      - step-cli
    image: nginx:1.25-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      # - "80:80"
      - "443:443"
    environment:
      - DOMAIN=${DOMAIN}
    volumes:
      - wordpress:/var/www/html
      - certs:/certs
      - ./templates:/etc/nginx/templates
    networks:
      - app-network


  step-cli:
    container_name: cli
    image: smallstep/step-cli
    user: root
    ports:
      - "80:80"
    environment:
      - PKI_DOMAIN_NAME=${PKI_DOMAIN_NAME}
      - DOMAIN=${DOMAIN}
    volumes:
      - certs:/home/step
      - ./request_certs.sh:/home/step/request_certs.sh
    command: ./request_certs.sh


volumes:
  step-etc:
  wordpress:
  dbdata:
  certs:


networks:
  app-network:
    driver: bridge