version: '3'

services:
  # step-ca:
  #   image: smallstep/step-ca:0.25.0
  #   container_name: step-ca
  #   ports:
  #     - 9000:9000
  #   volumes:
  #     - step:/home/step
  #   environment:
  #     - DOCKER_STEPCA_INIT_NAME=${CA_NAME}
  #     - DOCKER_STEPCA_INIT_DNS_NAMES=${ALLOWED_INCOMING_NAMES}
  #     - DOCKER_STEPCA_INIT_PASSWORD=${CA_PASSWORD}
  #     - DOCKER_STEPCA_INIT_REMOTE_MANAGEMENT=${ALLOW_REMOTE_MANAGEMENT}
  #     - DOCKER_STEPCA_INIT_ACME=true

  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=MYSQL_USER
    volumes: 
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=caching_sha2_password instead'
    networks:
      - app-network

  wordpress:
    depends_on: 
      - db
    image: wordpress:5.1.1-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - app-network

  webserver:
    depends_on:
      - wordpress
    image: nginx:1.15.12-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
    networks:
      - app-network

  certbot:
    depends_on:
      - webserver
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    command: certonly --webroot --webroot-path=/var/www/html --email sammy@projectpki.be --agree-tos --no-eff-email -d wordpress.pki.project -d www.wordpress.pki.project

volumes:
  certbot-etc:
  wordpress:
  dbdata:
  step:

networks:
  app-network:
    driver: bridge