version: "3.2"
services:
  step-ca:
    image: smallstep/step-ca:0.25.0
    ports:
      - 9000:9000
    volumes:
      - ./ca-data:/home/step
    environment:
      - DOCKER_STEPCA_INIT_NAME=${CA_NAME}
      - DOCKER_STEPCA_INIT_DNS_NAMES=${ALLOWED_INCOMING_NAMES}
      - DOCKER_STEPCA_INIT_PASSWORD=${CA_PASSWORD}
      - DOCKER_STEPCA_INIT_REMOTE_MANAGEMENT=${ALLOW_REMOTE_MANAGEMENT}
      - DOCKER_STEPCA_INIT_ACME=true
      