version: "3.2"
name: pki
services:
  ca.pki.project:
    container_name: ca.pki.project
    image: smallstep/step-ca:0.25.0
    ports:
      - 9000:9000
    volumes:
      - ./step-ca-data:/home/step
    environment:
      - DOCKER_STEPCA_INIT_NAME=${CA_NAME}
      - DOCKER_STEPCA_INIT_DNS_NAMES=${ALLOWED_INCOMING_NAMES}
      - DOCKER_STEPCA_INIT_REMOTE_MANAGEMENT=${ALLOW_REMOTE_MANAGEMENT}
      - DOCKER_STEPCA_INIT_ACME=true

  certs.pki.project:
    depends_on:
      - ca.pki.project
    container_name: certs.pki.projects
    image: nginx
    volumes:
    - ./step-ca-data/certs:/usr/share/nginx/data/:ro
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
    - "8080:8080"
    environment:
    - NGINX_PORT=80
    # THIS NEEDS TO BE CHANGED. THIS IS NOT A PROPER WAY TO DO IT. BUT I AM INCAPABLE !
    command: >
      sh -c "cp /usr/share/nginx/data/* /media/. &&
             chown -R www-data:www-data /media/ &&
             chmod 755 /media/* &&
             nginx
             sleep infinity"

  dns.pki.projects:
    depends_on:
      - certs.pki.project
    container_name: dns.pki.project
    image: technitium/dns-server
    ports:
      - "53:53/udp" #DNS service
      - "53:53/tcp" #DNS service
      - 853:853
      - 8081:8081
      - 8443:8443
    environment:
      - DNS_SERVER_DOMAIN=pki.project
      - DNS_SERVER_WEB_SERVICE_HTTP_PORT=8081
      - DNS_SERVER_WEB_SERVICE_HTTPS_PORT=8443
      - DNS_SERVER_FORWARDERS=1.1.1.1
      - DNS_SERVER_WEB_SERVICE_ENABLE_HTTPS=true
      - FINGERPRINT_OF_ROOT_CERT=
    restart: unless-stopped
